### ISSUE TITLE
Date needs to be stored with TimeZone

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-be#73]
We have a problem with the date stored in the DB... It's being stored based on server time which is UTC. I noticed this when creating a July 4th BBQ event which showed up on the 3rd after I saved it. We will probably need to address this by saving the time zone with the date value and convert that to the local user's time zone according to their browser or based on the event location.

**Comment by PaulMEdwards** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Properly handle timezone differences between back-end & front-end](https://trello.com/c/fcIrAoeo/71-properly-handle-timezone-differences-between-back-end-front-end)

**Comment by PaulMEdwards** [comment]
Server time can vary depending on where it's running (local dev Docker instance vs. AWS RDS).

Discussed with team. @kyle-richardson proposed we should be able to handle this completely in the front-end and not have to modify the back-end schema. He suggested we always store the date as UTC by interrogating the browser to get the local device's time zone and use that to calculate the UTC date in unix time format which we then store to the DB. Therefore, dates will always be stored in UTC, regardless of the server's actual timezone.

Sounds good to me.

Here's a JavaScript snippet to get the time zone from the browser:
`const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;`

**Comment by kyle-richardson** [comment]
after working with the logic of this potential fix on the front end, I believe there will be a way to simplify the database and make all logic easier on the front end as well.

currently, there are 4 columns that reference date/time: date, startTime, endTime, and createDateTime.

Since startTime and date are both required fields in any event type data mutation, I propose we remove the date column entirely, and have the remaining 3 fields require full unix format (or database equivalent, where all parts of the date and time are specified. eg. 1590172200000(Date.getValue()) = 2020-05-22T18:30:00.000Z(Date.toISOString()) = Fri May 22 2020 13:30:00 GMT-0500 (Central Daylight Time) (Date.toString()) = Fri, 22 May 2020 18:30:00 GMT (Date.toGMTString()).

This will have 2 benefits: 
1) it will remove column of database and simplify interactions with it
2) more importantly, it will remove an inherent issue with having just date value separate from time in regards to time zone.  eg.  If an event is created for 10:00pm May 22, 2020 in California (PDT), that same event would show as 12:00am May 22, 2020 in Texas (CDT), since the date is calculated separate from the time currently, without invoking way more logical data mutations than is necessary for a time zone difference calculation. By having the start time include the full date, we can simply use the Date prototype, momentjs or other library functions to easily mutate the full ISO or UNIX time into the other time zones and render it accordingly on the front end UI

**Comment by PaulMEdwards** [comment]
Works for me. In fact I was actually thinking the same thing. I'll do the needful.
